### ISSUE TITLE
Error when searching with Russian symbols

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-plugin-simplesearch#101]
I can't search with using RU symbols. 
I use  `grav-skeleton-rtfm-site` theme and use word `обновление` for example. 
I get `500 Internal Server Error` in console:
```
{"error":{"type":"Whoops\\Exception\\ErrorException","message":"mb_stripos(): Empty delimiter","file"
:"C:\\OpenServer\\domains\\gravlearn\\user\\plugins\\simplesearch\\simplesearch.php","line":243}}
```

Screen:
![image](https://cloud.githubusercontent.com/assets/7556290/23350329/eee71558-fd0d-11e6-992c-71a7cde35a7e.png)

How to fix?

**Comment by flaviocopes** [comment]
Turn off `ignore_accented_characters` in the plugin configuration. It only works with en_US locale installed on the server. 

It defaults to "true" now, I'm going to make this default to false.

**Comment by Sogl** [comment]
@flaviocopes Works without errors now, but results (left panel chapters and docs)  is always empty:
```
{"results":[]}
```

But content highlighting works fine:

![image](https://cloud.githubusercontent.com/assets/7556290/23382466/62a1ab42-fd96-11e6-85e2-98c88ec36dff.png)

**Comment by flaviocopes** [comment]
Works fine to me on a Learn2 site setup:

![screen shot 2017-02-28 at 14 13 26](https://cloud.githubusercontent.com/assets/11783388/23406626/2a5ba11e-fdc0-11e6-8d4f-ca8d8bcd1d52.png)


![screen shot 2017-02-28 at 14 13 20](https://cloud.githubusercontent.com/assets/11783388/23406625/286f7402-fdc0-11e6-92bd-3b1b342d9fe9.png)

**Comment by Sogl** [comment]
Where I can find the problem? I use `grav-skeleton-rtfm-site`.

**Comment by Sogl** [comment]
@rhukster @flaviocopes Still can't search through menu.

Whan I see when search `topic` word:

![image](https://cloud.githubusercontent.com/assets/7556290/25157154/32fdb8dc-24eb-11e7-9f36-ce3af027bf48.png)


Console:

![image](https://cloud.githubusercontent.com/assets/7556290/25157165/3d8ba17e-24eb-11e7-975b-aed94d358efa.png)

And what I see when type `обновление` after:

![image](https://cloud.githubusercontent.com/assets/7556290/25157183/5b7592da-24eb-11e7-87f2-0ecbd58b49d9.png)

Console:

![image](https://cloud.githubusercontent.com/assets/7556290/25157190/6bf483fa-24eb-11e7-9b17-dbb18877e603.png)

---
SimpleSearch 1.10.1

Settings:
![image](https://cloud.githubusercontent.com/assets/7556290/25157234/a9c43e28-24eb-11e7-8c4b-282b11bf36e2.png)

**Comment by flaviocopes** [comment]
As I said up, 

> Turn off ignore_accented_characters in the plugin configuration. It only works with en_US locale installed on the server.

**Comment by Sogl** [comment]
@flaviocopes As you can see from my screenshot, this setting is disabled.
I'm also use latest version where it's disabled by default.

**Comment by flaviocopes** [comment]
Sorry, got tricked by the green button. Not sure what could be the problem, the bulk of the comparison is here, look if it's going in the "else" correctly: https://github.com/getgrav/grav-plugin-simplesearch/blob/develop/simplesearch.php#L289-L302
