### ISSUE TITLE
Russian sympols search problems in version 1.10

### ISSUE THREAD

**Issue by ktaranov** [getgrav/grav-plugin-simplesearch#107]
Hi, guys.

Trying to search any Russian word and get error: `mb_stripos(): Empty delimiter` on  `…\user\plugins\simplesearch\simplesearch.php 243`.

Problem in function matchText line 243:
```php
$result = mb_stripos(iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $haystack), iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $needle));
```
If I rollback simplesearch.php on previous version (plugin version 1.9.3, where not used matchText function)  search for Russian words works fine.

Could you fix this issue?

**Comment by flaviocopes** [comment]
Turn off `Ignore accented characters` in the plugin configuration.

**Comment by flaviocopes** [comment]
Should be solved in the next release
