### ISSUE TITLE
no search results

### ISSUE THREAD

**Issue by rapsli** [getgrav/grav-plugin-simplesearch#109]
I have installed simplesearch on a clean new Grav installation and have created a yaml configuration file. 

The search page appears, but there are no search results. It seems as if the index is empty. Any ideas on how to fix this?

**Comment by flaviocopes** [comment]
By default the plugin searches in all pages with the taxonomy category set to 'blog': https://github.com/getgrav/grav-plugin-simplesearch/blob/develop/simplesearch.yaml#L7-L8 it works for blog posts, but in case you're using a different pages structure, you need to change it. Read more on https://github.com/getgrav/grav-plugin-simplesearch/#config-options

**Comment by rapsli** [comment]
thanks. I have removed too much that's why it didn't work. All good now.
