### ISSUE TITLE
No page when filter is empty.

### ISSUE THREAD

**Issue by bartwitt** [getgrav/grav-plugin-simplesearch#110]
Hello.

I hope there is nothing stupid I'm missing...

The problem is I want to have the full site searched, but  when I leave filters empty (as described in the docs), I get a 500 error.

![image](https://cloud.githubusercontent.com/assets/4354884/24996963/29b212ba-2035-11e7-8b12-a236f6fa8fc6.png)
![image](https://cloud.githubusercontent.com/assets/4354884/24997079/961e33e8-2035-11e7-89fe-8ccfd6a1e1b9.png)

When I completely remove the filter option from the config (which makes it use the default), it works but there are no results since I don't have category: blog on every page.

I can't see any errors in the php log.
![image](https://cloud.githubusercontent.com/assets/4354884/24997224/22b52dca-2036-11e7-9c57-63bb9d33393d.png)

Hope someone can help! Thanks.

**Comment by flaviocopes** [comment]
Should work fine. Also try `filters: null`. A 500 error could mean anything, look in your PHP error log to check what it says, or turn on the display errors feature in the System configuration.

**Comment by bartwitt** [comment]
`filters: null` instead of `filters: ` fixed it for me indeed. Pretty sure leaving it blank is what causes the error.

Thanks! Usually work with js, not php, so these things are bit tricky then ;)
