### ISSUE TITLE
Error on collections when no user logged in

### ISSUE THREAD

**Issue by lulis** [getgrav/grav-plugin-simplesearch#111]
As mentioned [here](https://github.com/getgrav/grav-plugin-simplesearch/pull/102#issuecomment-294309044), pull #102 breaks simplesearch plugin when no user logged in.

Got the following error on [this line]( https://github.com/getgrav/grav-plugin-simplesearch/pull/102/files#diff-f251bc5bb2e7099451e82741253d30cfR231)):

 **Identifier "user" is not defined.** 

I'm not using any kind of login in grav, only normal public pages.

Have to comment the call of `checkForPermissions` ([here](https://github.com/getgrav/grav-plugin-simplesearch/pull/102/files#diff-f251bc5bb2e7099451e82741253d30cfR170
)) as workaround.

**Comment by flaviocopes** [comment]
PR merged!
