### ISSUE TITLE
Only blog page get result from search

### ISSUE THREAD

**Issue by blackyzero** [getgrav/grav-plugin-simplesearch#116]
Hi everyone,

i installed and enabled simplesearch plugin, however only blog pages which are set as "blog" in category can give the result result.
Other pages which are created from different taxonomy and tag are not showing in search result.
I tried to empty the "Category filter" (as attached image), and also tried to put filters: "" in user/config/plugins/simplesearch.yaml, none of them works.

Could you please show me how to fix it?

<img width="1026" alt="screen shot 2017-05-24 at 1 35 59 pm" src="https://cloud.githubusercontent.com/assets/4286063/26389818/f7aed76e-4085-11e7-985d-1feeb707dbb8.png">

**Comment by blackyzero** [comment]
i got it works after adding following entry into simplesearch.yaml
filters: ""

**Comment by flaviocopes** [comment]
You stumbled on an issue that I fixed this week, see the last 2 commits here: https://github.com/getgrav/grav-plugin-simplesearch/commits/develop

The problem is that adding an empty line in the category filter in Admin falls back to the default, which is filter by "blog" category.

I added a "@none" keyword that will serve that need.

**Comment by flaviocopes** [comment]
The problem is that setting in the yaml, next time you save in Admin, the changes will be overwritten. Try my solution and let me know if it works fine for you, I'll then make a release

**Comment by blackyzero** [comment]
thanks @flaviocopes for your comment,
This doesn't work after following your instruction,

I added "@none" into Category filter, as below
<img width="1297" alt="screen shot 2017-05-25 at 12 56 03 pm" src="https://cloud.githubusercontent.com/assets/4286063/26437821/9455c582-4149-11e7-8585-47e14180da7a.png">

After saving the config, the file /user/config/plugin/simplesearch.yaml
`enabled: true
built_in_css: true
display_button: false
min_query_length: 3
route: /search
template: simplesearch_results
filters:
  category:
    - '@none'
filter_combinator: and
ignore_accented_characters: false
order:
  by: date
  dir: desc
`

**Comment by flaviocopes** [comment]
Strange! It's not yet released, did you checkout the latest develop branch?

**Comment by blackyzero** [comment]
i am using v1.10.2, i am installing from admin interface.

**Comment by flaviocopes** [comment]
The latest release should fix it. In the plugin configuration through Admin, set @none in the category filter.
