### ISSUE TITLE
Possible bug with multilanguage setting

### ISSUE THREAD

**Issue by reachcontent** [getgrav/grav-plugin-simplesearch#13]
Error occurs only with language setting not left blank (examples used: en-US, fr-FR…) in the Admin:

> _Settings > Language > Supported (first field)_

`An exception has been thrown during the rendering of a template ("Invalid argument supplied for foreach()") in "simplesearch_results.html.twig" at line 12.`

`Open: /srv/data/web/vhosts/domain.tld/htdocs/vendor/twig/twig/lib/Twig/Templ ate.php`

`if (false === $e->getTemplateLine()) {`

`$e->setTemplateLine(-1);`

`$e->guess();`

`}`

`throw $e;`

`} catch (Exception $e) {`

`throw new Twig_Error_Runtime(sprintf('An exception has been thrown during the rendering of a template ("%s").', $e->getMessage()), -1, $template->getTemplateName(), $e);`

`}`

`} elseif (false !== $parent = $this->getParent($context)) {`

**Comment by rhukster** [comment]
I'm having trouble recreating this.. I have a test multi-language site and search seems to work fine in both languages.  Can you please provide me step-by-step instructions on how to recreate the problem?

**Comment by reachcontent** [comment]
I just recreated it on my main website (reachcontent.com) but I must admit I have postponed the update to the latest SimpleSearch version (currently I am staying with 1.4.1). I guess I would have to implement inheritance for my customization (FR locale).
I just added `fr` to the Supported languages Config field.
Will update later today to check if I can still reproduce it. Thanks for your time)

**Comment by reachcontent** [comment]
As expected I get the same result after updating the plugin to v1.5.0

1. I add a supported language in the admin: Configuration > System > Languages (first field). I then just go from a blank _Supported_ field to one with `fr`
2. I perform a search on the website

**Comment by rhukster** [comment]
Ok thanks this will help.

**Comment by reachcontent** [comment]
Is it somewhat linked with what you fixed in Grav #228?
https://github.com/getgrav/grav/issues/228

**Comment by rhukster** [comment]
It could be, but I sort of doubt it! I have it all linked on my local, but by default the lang codes are enabled. I'll try turning off the option and see if it makes any difference.

**Comment by reachcontent** [comment]
Still there after 1.5.1 update (check website).

**Comment by rhukster** [comment]
Can I please get a copy of your user/ folder zipped up so i can test locally?

**Comment by rhukster** [comment]
Fixed with this: https://github.com/getgrav/grav/commit/7cb7891fa77b5f7ba667da207817fff01b307142
