### ISSUE TITLE
Not working with Grav's Admin Panel

### ISSUE THREAD

**Issue by jpfleury** [getgrav/grav-plugin-simplesearch#14]
The plugin SimpleSearch can't be configured using the Admin Panel. For example, if we go to the settings page of the plugin (url `/admin/plugins/simplesearch`) and click on *Save*, there's the following error:

> **Validation failed:** order is not defined in blueprints

My config: Grav v0.9.39, Admin Panel v0.4.2, SimpleSearch v1.4.0

**Comment by flaviocopes** [comment]
Thanks for reporting!
