### ISSUE TITLE
simplesearch.php has a XSS vulnerability

### ISSUE THREAD

**Issue by kolbma** [getgrav/grav-plugin-simplesearch#15]
Hi,
you read in query parameter.
You use query value unfiltered.
You put query parameter unfiltered in twig variables.
You use the variable as it is in the twig templates.
I hope this is an exceptional case and the rest of the code is more safe?!

Thx

**Comment by flaviocopes** [comment]
The query parameter is filtered through Grav\Common\Uri::query(). Can you provide an example of your bug report?

**Comment by kolbma** [comment]
call the url /search/query:%3Cscript%3Ealert(%27ups%27)%3B%3C%2Fscript%3E

**Comment by kolbma** [comment]
Btw. the http://demo.getgrav.org/ sites are not vulnerable. They report a server error. I'm interested in what you are using there in the platform stack to be not vulnerable. Thx.

**Comment by rhukster** [comment]
There is some CSF stuff at the Apache level of the server.  However, i'm not able to replicate on my local either because I can't even get that query to route:

![2015-10-06-08-0pn8a](https://cloud.githubusercontent.com/assets/1084697/10311849/b30b0da4-6c05-11e5-939f-e385b373d99c.png)

**Comment by kolbma** [comment]
Ah I know why: RewriteCond %{QUERY_STRING} (<|%3C)([^s]*s)+cript.*(>|%3E) [NC,OR]
But nevertheless the application itself is vulnerable.

**Comment by rhukster** [comment]
I'm trying to test with all that stuff removed from .htaccess, and I still can't get it route and cause a problem.. will continue testing!

**Comment by rhukster** [comment]
I'm having trouble properly recreating your scenario, but please test with this potential fix: https://github.com/getgrav/grav/commit/12101f6014f46238a899f3d50137a2f93ffa865c

**Comment by kolbma** [comment]
It's somehow related to the htaccess configuration.
If you insist on this rewrite rules you shouldn't suggest "If you experience problems on your site block out the operations listed below" and make clear that the security of the application is based on this.
This block sounds like some optional filter.
I'm using lighttpd here and its rewrite feature is limited.
![ups](https://cloud.githubusercontent.com/assets/5228369/10312829/10cfc35c-6c4d-11e5-8e2d-5ba2fe27a917.jpg)

I'll have a look  at the patch...

**Comment by kolbma** [comment]
The patch does its job.

**Comment by rhukster** [comment]
OK thanks, will release an update with this today.
