### ISSUE TITLE
SimpleSearch plugin does not work because...

### ISSUE THREAD

**Issue by petira** [getgrav/grav-plugin-simplesearch#158]
The SimpleSearch plugin did not work. I was looking for a solution in the previous posts and found out that I was not the only one who had the problem.

The solution, of course, is to change the default settings, specifically to clear the `blog` value in the `simplesearch.yaml` file, as described in `README.md`.

Specifically, modify the default setting from

```
...
filters:
     category: blog
...
```

to

```
...
filters:
     category: []
...
```

or to

```
...
filters:
     category:
...
```

Both settings work.

**What is important, however, is that the change must be done directly in the `simplesearch.yaml` file!** Because if the change is done via the Admin plugin, the above lines will be completely deleted

```
...
...
```

and the SimpleSearch plugin does not work. **This is a real bug when making changes to the settings via the graphical interface SimpleSearch plugin.**

> SimpleSearch v1.14.1
> Admin Panel v1.8.1
> Grav v1.4.5

**Comment by khartahk** [comment]
I can confirm this helps.

**Comment by petira** [comment]
In other words, the same problem and possible (but not ideal) solution (#140). I'm convinced that a plugin fix is necessary.

**Comment by jneuendorf** [comment]
#113 seems to be a related issues, too.
