### ISSUE TITLE
Simplesearch behavior on »umlauts«

### ISSUE THREAD

**Issue by bjoern-weiler** [getgrav/grav-plugin-simplesearch#16]
When searching a minor umlaut no capital umlaut is found by simplesearch (and reverse).

**Comment by rhukster** [comment]
This should be sorted?

![2015-10-14-17-n29c7](https://cloud.githubusercontent.com/assets/1084697/10500781/4027d210-7298-11e5-8a41-f9e18c96463c.png)

**Comment by bjoern-weiler** [comment]
Perfect. Tanks!
