### ISSUE TITLE
Not Working at with Grav Bata or RC

### ISSUE THREAD

**Issue by Umbyology** [getgrav/grav-plugin-simplesearch#188]
FYI ... I noticed this happen for a while now, the results yield an error 404. It seems that the search address is leaving off the domain TLD ...

`https://search/query:search-words`

the address should be ...

`https://my-domain-name/search/query:search-words`

I've tried playing with the plugin settings, but no change.

**Comment by rhukster** [comment]
i can't replicate this.. search works fine for me. can you give me instructions on how you set this up?

**Comment by Umbyology** [comment]
I'm using GRAV 1.7 RC10 with the Hadron theme. Fresh install. Everything updated. Here is a screenie of the settings.

The site is at ... https://www.umbyology.com

<img width="1320" alt="simplesearch-settings" src="https://user-images.githubusercontent.com/22547499/81879262-dd8a3a00-954f-11ea-882f-81247663ea76.png">

**Comment by Umbyology** [comment]
I just updated to the latest version of simplesearch. If you go straight to the Search Page (/search) it works fine. So, the issue must be in the theme's search field at the top of the site.

**Comment by rhukster** [comment]
It does sound theme related. I suggest you ask on the RocketTheme forums as the guys there know Gantry5 better and might have a quick fix for the search particle

**Comment by Umbyology** [comment]
Ya I tried there, they thought it might be the plugin, so I tried here. I'll head back over there.

Thanks bud!
