### ISSUE TITLE
opt-out by setting  simplesearch: process to false does not seem to work

### ISSUE THREAD

**Issue by awrog** [getgrav/grav-plugin-simplesearch#192]
Header of my page
```
simplesearch:
    process: false
```
Cleared all caching. Page still shows up in search [result](https://lrp-netwerk.pkn.nl/search/query:mendix%208)

**Comment by ezchile** [comment]
I have the same issue.

**Comment by rhukster** [comment]
Just tested this with latest and it works for me.  I had a page showed in the results, added:

```
simplesearch:
  process: false
```

and now it doesn't show in the results. BTW, this ONLY works for regular pages, not modular sub pages.

**Comment by awrog** [comment]
After updating tor the latest version of the plugin, it now works. I was
stillon v2.2.0

Thanks!
