### ISSUE TITLE
Error on some search terms when enabling multi language

### ISSUE THREAD

**Issue by zemmediamatiker** [getgrav/grav-plugin-simplesearch#20]
I have created a manual with Grav which first started german-only. It all worked fine with the simple search and I never got an error. But as Switzerland is multi language, I needed to implement the whole content in french. So I used the powerful multi language ability of Grav and with the content it all worked fine as expected. But when entering the first search term, I was a little bit confused. I always got an Crickey! - Error on some but not all search terms. But more confusing was, that I can't see any logical sense, which terms are causing an error and which ones are not.

Because the standard search form which is provided with simple search doesn't work for me (enter doesn't search) I decided to create my own input field. 

If you enter a search term like "Auto" it will give a Error. (`path/de/search/query:auto`)
If you enter a search term like "Soldat" it will show up the results. (`path/de/search/query:soldat`)

I tried to use my `user` - folder on a clean installation - it gave me the same error. Also on a webspace instead of locally on MAMP (tested on two Macs) the problem appears.

Because I'm in apprentiship and my supervisor wanted to show me Git, my project is on GitHub, so you can recreate it:
[Link to GitHub Repo (dev)](https://github.com/ZEM-Mediamatiker/DIGAME-Handbuch/tree/dev)

**Comment by rhukster** [comment]
Fixed with: https://github.com/getgrav/grav/commit/7cb7891fa77b5f7ba667da207817fff01b307142
