### ISSUE TITLE
Search pages not visible and routable

### ISSUE THREAD

**Issue by Jogai** [getgrav/grav-plugin-simplesearch#200]
The search does not return pages that have both visible and routable set to false. Is there something I can do to fix that? I have a lot of pages and they should not be visible in the menu, but still be searchable.

**Comment by rhukster** [comment]
the `routable: false` means they can't be reached, so a search result would have nothing it could link to. That's why it's internally skipped.

**Comment by Jogai** [comment]
Makes sense. I use it as a phonebook, so the entries dont need their own page. But I can disable the link in the templates. Thank you for the fast answer.
