### ISSUE TITLE
Empty search results

### ISSUE THREAD

**Issue by loranger** [getgrav/grav-plugin-simplesearch#23]
Hello,

I tried to install simplesearch on a fresh grav install. Il only have one page which is the default homepage installed with the antimatter theme.
I tried to remove the
```yaml
filters:
  category:
    - blog
```
part in order to search all the pages (the only page, actually) but I can't make it work. I tried some simple queries such as `skeleton`or `page`but the search result is always empty (0 results).

Did I missed something important ?

**Comment by rhukster** [comment]
The code to allow for the removal of `filters:` was pushed in develop, but not released.  The 1.6.0 release has this fix now.

**Comment by loranger** [comment]
Awesome, thank you !
