### ISSUE TITLE
simplesearch.css will not include properly

### ISSUE THREAD

**Issue by oscon** [getgrav/grav-plugin-simplesearch#24]
using skeleton twentyfifteen the simplesearch.css will not used properly:
the definitions in user\plugins\simplesearch\css\simplesearch.css will not be shown.
wrong directory?
![2015-11-17 17_00_02-search results _ grav](https://cloud.githubusercontent.com/assets/478932/11217258/b3939ce4-8d4f-11e5-97f0-0a6df13c0d04.jpg)

**Comment by flaviocopes** [comment]
This is a bug in the twentyfifteen template. I'll add a fix now to that theme, then the skeleton will be rebuilt. 

You can fix it yourself now, without waiting for the release, by adding `{{ assets.css() }}` at line 24 of `user/themes/twentyfifteen/templates/partials/base.html.twig`
