### ISSUE TITLE
Page distorted in SimpleSearch results

### ISSUE THREAD

**Issue by Endogen** [getgrav/grav-plugin-simplesearch#25]
I just installed the SimpleSearch plugin and generally i'm happy :) but when i let the plugin search every page, and when i search for something that the default HOME page of Grav includes, then i get this result:
![distorted](https://cloud.githubusercontent.com/assets/226475/11700015/8fcdd3b8-9ec7-11e5-8780-ae1c2b7e1ae9.png)

The titles are to close together and the note about the skeletons isn't at it should be.

**Comment by flaviocopes** [comment]
This is because the search plugin returns a portion of the page content if no summary is found. Add a summary for the home page (http://learn.getgrav.org/content/content-pages#summary-size-and-separator) or limit the search to the blog posts.

**Comment by Endogen** [comment]
The page summary is enabled and even if i add the summary delimiter "===" after the first paragraph, the title is distorted. I have to say that i don't care that much about it but for my understanding the displaying of search results should not change the visual representation of the page. I don't know if that's technically possible but that is what i would expect.

**Comment by rhukster** [comment]
This is simply a case of the CSS for antimatter theme not expecting the title to be displayed in this location, hence the padding/margin is not correct.  It's not a code issue.

**Comment by Endogen** [comment]
Thanks for letting me know
