### ISSUE TITLE
No results found when searching by taxonomies

### ISSUE THREAD

**Issue by khanduras** [getgrav/grav-plugin-simplesearch#28]
It doesn't look like SimpleSearch is allowing query by keyword. 

It looks like it's [attempting to find pages](https://github.com/getgrav/grav-plugin-simplesearch/blob/develop/simplesearch.php#L154-L165) by taxonomies but I feel that [this line](https://github.com/getgrav/grav-plugin-simplesearch/blob/develop/simplesearch.php#L167) is taking out the pages that would be found by taxonomy. 

To confirm, if you [browse by category](http://chiefqualakon.net/news/tag:journal) you can find posts but when you [search by that category](http://chiefqualakon.net/search/query:journal) it doesn't find any results.

Cheers!

**Comment by rhukster** [comment]
Should be sorted now in develop.  Taxonomy searching is enabled by default, but can be restricted or disabled via `filters: '@taxonomy'`
