### ISSUE TITLE
Multilang Support

### ISSUE THREAD

**Issue by ArnCo** [getgrav/grav-plugin-simplesearch#29]
Hey guys,

Is multilang supported by SimpleSearch? I have had problems to set it up, creating /en or /fr directories under the template directory do not seem to work (problems with paths...).

Would it be possible to have a working example ?

Thanks for your time,

ArnCo

**Comment by flaviocopes** [comment]
Yes it works. 

You mention "creating /en or /fr directories under the template directory". You don't need to do that.

I tried installing on the "Multilang Site Skeleton", added the search box and it searches just in the active language.
