### ISSUE TITLE
Access the JSON search results

### ISSUE THREAD

**Issue by khanduras** [getgrav/grav-plugin-simplesearch#5]
Trying to get a search dropdown to work, how can I access the json twig template? Would this have to be by a route?

**Comment by rhukster** [comment]
You can use this snippet:

https://github.com/getgrav/grav-plugin-simplesearch/blob/develop/templates/partials/simplesearch_searchbox.html.twig

it's already loaded by the plugin, just include the `partials/simplesearch.html.twig` template, or copy it into your plugin/theme and edit it and use that.

**Comment by khanduras** [comment]
I can make search work, but I want to expose the json for a particular input field before hitting enter.

Do you think a route could be created like so:

```
http://localhost/grav_site/search/json:jungle
```

It would simply display the twig template with the appropriate json for the term provided. Ideally it would search Title, URL, tags and summary. Currently if I include simplesearch_results.json.twig it doesn't allow me to put in new search terms and I don't know if that meta/header data is exposed to search_result in search_results.

**Comment by rhukster** [comment]
Oh it already works.  Basically the search normally works like this:

```
http://yoursite.com/grav/search/query:jungle
```

but Grav also works with any other extensions like `.xml` or `.json`, you just need to provide a corresponding Twig file.  So as well as the default `.html`:`search.html.twig`, you provide a json one called `search.json.twig` and then query like this:

```
http://yoursite.com/grav/search.json/query:jungle
```
