### ISSUE TITLE
Simple Search Error

### ISSUE THREAD

**Issue by jhochgreve** [getgrav/grav-plugin-simplesearch#50]
Hey guys!

I am wondering what I may be doing wrong here. I am adding simplesearch to an existing pre-planned search input that I have in a partial for my theme. I am getting the below error: 

"Unexpected character "&" in "@Page:/user/plugins/error/pages" at line 1."

I attached the searchbox partial which I customized to match my theme and the template I customized and added to my theme:

[simplesearch_results.txt](https://github.com/getgrav/grav-plugin-simplesearch/files/366707/simplesearch_results.txt)
[simplesearch_searchbox.txt](https://github.com/getgrav/grav-plugin-simplesearch/files/366708/simplesearch_searchbox.txt)

I am curious if this is a bug or perhaps I have overlooked something in the documentation. It appears that all of the simplesearch yaml files exist and are in the plugins directory where they should be, and match up with the documentation. 

Any help would be greatly appreciated!

**Comment by flaviocopes** [comment]
Cannot replicate this! Can you PM me your user/ folder to test in gitter.im/flaviocopes? Thanks!

**Comment by jhochgreve** [comment]
PMed you a repo in gitter.im thanks for looking at this! I do plan to have multiple instances of it on the site so it's huge to get it working for me.

**Comment by flaviocopes** [comment]
The original `Unexpected character "&"` issue was a conflict between Error and Smartypants plugins.

Released https://github.com/getgrav/grav-plugin-error/releases/tag/1.5.1, available soon in the GPM, should be fixed!
