### ISSUE TITLE
not sure if this can be solved

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav-plugin-simplesearch#54]
Hi, 

It seems that when searching for a specific word in Romanian we have a small issue.

When the official and traditional language is used with words containing **șțâăî** in the title and articles, a search without this characters will be null and wont find anyting.

Is there a way that the characters mentioned above could be changed to their representation without the *\* special  ,  etc ...*\* while doing the search ? as an example:

title of article is : Cum să înțelegem gramatica. when searching for "Cum sa intelegem gramatica" the result is nowhere due to the different characters (of course). 

If when introducing the normal characters there could be a  transformation of either the "article title" or the "text introduced" to be grammatically correct then a proper result will occur.

Not sure which is easier or even possible to do considering the Romanian language is not hugely spoken over the world and it seems that not even popular with Developers (Google, Microsoft, Apple, Adobe ... since it took  them almost 30 years to implement the special characters, not to mention the translation which is not there yet).

Just a thought - could this be a valid thin in French, Spanish etc .. ? replacing the characters with the proper ones containing " ș ț â ă î a à á â" etc ... ?

**Comment by flaviocopes** [comment]
This is probably a good improvement, maybe these special chars could optionally be "normalized" both in the search string, and in the pages titles https://stackoverflow.com/questions/9720665/how-to-convert-special-characters-to-normal-characters

**Comment by JohnMica** [comment]
Hi Flavio,

Thing is the other way around - most people type things without the special char in the search bar (for Romanian for sure) - the issue could be changing the right ones into special chars and then do the search ... Or do the search for both normal char as entered and for the replaced chard (kind of a loop and when a result of found then return it? Can the solution be applied to such a logic? Hope this makes sense. 

John

**Comment by stegrams** [comment]
@JohnMica  I found that [transliterator_transliterate](http://php.net/manual/en/transliterator.transliterate.php) do the job.
I tested all the examples you gave, + some Greek ones, like..
```php
echo transliterator_transliterate('Any-latin; Latin-ASCII;',$example);
```
and worked as expected.
But I had to install [php intl](http://php.net/manual/en/book.intl.php) for I18n functions

**Comment by flaviocopes** [comment]
The option to ignore accented characters has been added in version 1.10.0 thanks to https://github.com/getgrav/grav-plugin-simplesearch/pull/89
