### ISSUE TITLE
Pressing "Enter" does not trigger the search

### ISSUE THREAD

**Issue by 01010000101001100** [getgrav/grav-plugin-simplesearch#55]
Tested both on newest Safari and Chrome - in both cases I cannot trigger search by pressing "Enter" inside search field.

**UPDATE:** I know why is this happening - it's because it's calling jQuery that it's not there yet - I am adding all JS at the bottom of each page and this script is trying to execute something earlier. How can I append the JS for search after all other assets?

**Comment by Swader** [comment]
Fixed by #57

**Comment by flaviocopes** [comment]
#57 merged, closing
