### ISSUE TITLE
throw new \RuntimeException('Page Not Found', 404); Exception-Search is not working with custom taxonomy

### ISSUE THREAD

**Issue by anmolgupta1** [getgrav/grav-plugin-simplesearch#56]
throw new \RuntimeException('Page Not Found', 404); Exception-Search is not working with custom taxonomy..
have a listing page called instructors and several item with name instructor. I want to add search functionality to this listing page like a blog page, but there is error coming each time i search any item ..
i also checked directly by entering  url http://localhost/abc/instructors/search/query:ada but same error.
I have added category : -instructors to head of instructors.md file..

kindly help

**Comment by flaviocopes** [comment]
Please provide as many details as you can to recreate the issue:

- the relevant page structure (attach a zip of a subset of `user/pages` if needed)
- the plugin's config file /user/config/plugins/simplesearch.yaml

**Comment by anmolgupta1** [comment]
simplesearch.yaml

enabled: true
built_in_css: true
display_button: false
min_query_length: 3
route: /search
template: simplesearch_results
filters:
  category: instructors
filter_combinator: and
order:
  by: title
  dir: desc


instructors.md
---
title: 'ABC'
menu: 'ABC'
blog_url: instructors
content:
    items: '@self.children'
    order:
        by: date
        dir: desc
    limit: 100
    pagination: true
feed:
    description: 'ABC.'
    limit: 0
pagination: false
taxonomy:
    category:
        - instructors
---


instructor.md

---
title: 'AB'
date: '07-07-2014 17:27'
metadata:
    description: 'AB.'
sitemap:
    changefreq: monthly
taxonomy:
    tag:
        - 'Hong Kong'
   category:
        - China
        - certified
        - instructors
simplesearch:
    route: @self
    filters:
        - @self
        - @taxonomy: [category]
    filter_combinator: and
---

**Comment by anmolgupta1** [comment]
Any help?

**Comment by flaviocopes** [comment]
I don't get any problem by testing with the pages you listed. The problem must lie elsewhere. PM me you user/ folder via Gitter.im/flaviocopes and I'll see if I can replicate the problem locally.

**Comment by flaviocopes** [comment]
Closing as could not replicate
