### ISSUE TITLE
search results highlight

### ISSUE THREAD

**Issue by zemmediamatiker** [getgrav/grav-plugin-simplesearch#6]
I'd like it, if there was the possibility to not just find the pages matching the keyword but also hightlight the words in the found pages. something like, that
```
/mygravsite/search/query:camera
```
shows up the search results as it is now. but clicking on a result, all found keywords will be highlighted. Eventually with paragraphs in the url like this:
```
/mygravsite/products/smartphone?q=camera
```
Would be a nice addition to the plugin.
Thanks :)

**Comment by rhukster** [comment]
This is a bit specific to the theme in question.  I've added this functionality to the learn2 theme and you can see it in action on http://learn.getgrav.org
