### ISSUE TITLE
Some encoding problem with russian language

### ISSUE THREAD

**Issue by zeegin** [getgrav/grav-plugin-simplesearch#67]
![2016-08-12 02-23-53](https://cloud.githubusercontent.com/assets/729213/17608832/69a9d778-6040-11e6-99d7-0ca477e9ab4b.png)
![2016-08-12 02-26-27](https://cloud.githubusercontent.com/assets/729213/17608833/6b6ceb54-6040-11e6-90b0-9ab544ac9aad.png)

Server worked on IIS 8.5 on Windows Server2012 R2 with russian translation.
All russian translated operation system are working on cp1251 encoding.

        /** @var Uri $uri */
        $uri = $this->grav['uri'];
        $query = $uri->param('query') ?: $uri->query('query');
        $route = $this->config->get('plugins.simplesearch.route');

        $query = iconv('cp1251', 'utf-8', $query);//patch

Patch $query convertation can resolve this problem, but it's wrong way to solution and i do not sense how it shell be done.

Grav have no problem with opening files wich content is utf-8 encoding, have no problem with filenames with cp1251 encoding, but russian symbols in URL reed not correctly.

Regarding clean URL i mean use only eng charachters is true, but for this plugin URL can contant anything.

**Comment by zeegin** [comment]
Mayby some spatial server URL encoding configuration. I try to found how it can by resolve.

**Comment by zeegin** [comment]
I found, this problem was in FastCGI confuguration on Windows.
https://support.microsoft.com/en-us/kb/2277918

> This problem occurs because the FastCGI module in IIS 7.5 uses ASCII encoding when you set server variables. Therefore, the REQUEST_URI server variable is not set correctly when the URL contains UTF-8 characters.
`
reg add HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\w3svc\Parameters /v FastCGIUtf8ServerVariables /t REG_MULTI_SZ /d REQUEST_URI\0PATH_INFO`

> This example configures the FastCGI module to use UTF-8 encoding when you set the REQUEST_URI and PATH_INFO server variables.

**Comment by flaviocopes** [comment]
Glad you found out the configuration problem!
