### ISSUE TITLE
Searching for commas & spaces alone yields Server Error

### ISSUE THREAD

**Issue by gitname** [getgrav/grav-plugin-simplesearch#71]
When I search for a string consisting of only spaces, by entering those spaces (encoded as `%20`s) directly into the address bar, the Grav Blog Skeleton demo site shows a "Server Error" page. This is shown in the **Experiment C** section below.

---

**Experiment A**. Search for non-whitespace characters, using search form:

I get a "0 results" message. I consider this to be the "by design" behavior.

![image](https://cloud.githubusercontent.com/assets/7143133/18665111/78078c12-7eda-11e6-8724-1b28c5c82cb3.png)

Link: https://demo.getgrav.org/blog-skeleton/search/query:test

---

**Experiment B**. Search for whitespace characters only (i.e. 4 spaces, entered as `    `), using search form:

I get an "Error 404" page.

![image](https://cloud.githubusercontent.com/assets/7143133/18665140/9e429e44-7eda-11e6-97f3-cf4dfd4cbb51.png)

Link: https://demo.getgrav.org/blog-skeleton/search/query:

---

**Experiment C**: Search for whitespace characters only (i.e. 4 spaces, encoded as `%20%20%20%20`), using address bar:

I get a "Server Error" page containing information about the PHP code in use.

![image](https://cloud.githubusercontent.com/assets/7143133/18665227/0c6f9502-7edb-11e6-9a3d-2e1288640100.png)

Link: https://demo.getgrav.org/blog-skeleton/search/query:%20%20%20%20

**Comment by gitname** [comment]
**Experiment D**: I see the same **Server Error** page when I search for a lone comma (i.e. `,`).

Link: [https://demo.getgrav.org/blog-skeleton/search/query:,](https://demo.getgrav.org/blog-skeleton/search/query:,)

To demonstrate that this is not limited to searches performed by directly manipulating the URL; entering 2 spaces and a comma (i.e. ` ` ` ` ` ,`) in the search form in the Blog Skeleton demo site yields the same result (the client-side validation prohibits submission of a comma alone).

**Comment by gitname** [comment]
I see the same behavior on a site I am developing. On that site, I am running Grav v1.1.5, Admin v1.2.2, and SimpleSearch v1.9.2.

**Comment by coyoterj** [comment]
Hi,
When doing a search with comma at the end ( teste, ), this error occur:
![selecao_015](https://cloud.githubusercontent.com/assets/2916909/20609110/b227c1f0-b26f-11e6-9a1f-315a858364d3.png)

**Comment by flaviocopes** [comment]
Should be fixed now, if you can test @coyoterj @gitname

**Comment by flaviocopes** [comment]
(not yet released, but in develop

**Comment by coyoterj** [comment]
Hi @flaviocopes,

Tried to "bin/gpm update simplesearch", results:
"GPM Releases Configuration: Stable

Nothing to update."

Then, I updated the file simplesearch.php and that worked perfectly. ;)

Thanks!
