### ISSUE TITLE
Exception when disabling translations

### ISSUE THREAD

**Issue by l3d00m** [getgrav/grav-plugin-simplesearch#87]
If I set "Translations Enabled" to "No" and try to search for something, grav throws an exception. Similiar stacktrace and problem as #13:
```
An exception has been thrown during the rendering of a template ("Invalid argument supplied for foreach()") in "simplesearch_results.html.twig" at line 15.
```

Using search version v1.9.3 and newest grav (v1.1.9)

**Comment by flaviocopes** [comment]
Can't replicate, I get the untranslated screen:

![screen shot 2016-12-19 at 10 46 22](https://cloud.githubusercontent.com/assets/11783388/21308023/650186a0-c5d8-11e6-8d76-6b22cad7a184.png)

What theme are you using, and can you paste your `user/config/plugins/simplesearch.yaml` file?

**Comment by l3d00m** [comment]
I just tried it using a fresh grav install. I installed the search plugin, changed no settings in the plugin options and installed the *pinpress* theme. Disabling the "Translations Enabled" leads to an error:

![error](https://cloud.githubusercontent.com/assets/12055376/21308307/af459a2a-c5d9-11e6-9deb-9d11d955ad7b.JPG)

**Comment by flaviocopes** [comment]
Replicated on a fresh site too

**Comment by flaviocopes** [comment]
Was a Grav issue, now fixed in `develop` https://github.com/getgrav/grav/commit/442249c3a193220cf6578b07b537212dc9c8096c

**Comment by l3d00m** [comment]
Thank you. Grav is the easiest and best CMS I ever used, the fast support makes it even better :)
