### ISSUE TITLE
search doesnt work

### ISSUE THREAD

**Issue by jsox79** [getgrav/grav-plugin-simplesearch#92]
using default template and calling inside the page
/search/query:  works fine but the actual search bar does not respond. its like submit doesnt actually get called

simplesearch.yaml:

enabled: true
built_in_css: true
display_button: true
min_query_length: 3
route: /search
template: simplesearch_results
filters:

**Comment by flaviocopes** [comment]
There could be a JavaScript issue halting the script. Is there any error in the browser console? Also, happens with every browser (Chrome for example?)

**Comment by flaviocopes** [comment]
OR the theme does not load jQuery which is currently required. The current `develop` branch has a fix for this, removing the jQuery dependency. You can try moving https://github.com/getgrav/grav-plugin-simplesearch/archive/develop.zip to the `user/plugins/simplesearch` folder.

**Comment by jsox79** [comment]
thank you for the heads up, i cant believe i missed that.  i just added the
jquery framework and voila it fixed the problem.


Joshua Sox
Computer CPR
910 670 3960
