### ISSUE TITLE
Find nothing

### ISSUE THREAD

**Issue by Kuurusch** [getgrav/grav-plugin-simplesearch#94]
Hallo, I have the strange behaviour, that the search plugin cant find any word. Everything else works in Grav.

Any idea?

**Comment by rhukster** [comment]
Probably the search filters are not configured.  You have to configure which pages simple search is going to look at before it will find anything.

**Comment by Kuurusch** [comment]
Yea, my blog is under a folder (root)/home/blog and it was set to /blog. Maybe I have to set it to home/blog. I will try, thanks!

**Comment by Kuurusch** [comment]
@rhukster So I tried, it works only when I remove all settings under "filters" in the simplesearch.yaml file. when I set category: blog it doesn't work. I tried also category: home/blog

Any idea what is wrang?

**Comment by flaviocopes** [comment]
If you set `category: blog`, the blog posts must all have that taxonomy in their page header (see https://learn.getgrav.org/content/taxonomy#taxonomy-example). Is this the case?

**Comment by Kuurusch** [comment]
So, I have to edit each time I create a new blog post in its file header this taxonomy? Cant I create it over the admin-interface?

**Comment by flaviocopes** [comment]
Sure, you can do it via the Admin Plugin, "Options" tab of the page:

![screen shot 2017-02-24 at 17 10 29](https://cloud.githubusercontent.com/assets/11783388/23310849/34ba470a-fab4-11e6-9626-bb00bb59d085.png)

**Comment by flaviocopes** [comment]
When you're setting that taxonomy filter, it will only search in pages that have that taxonomy set.

**Comment by Kuurusch** [comment]
ou, ah ok, thanks a lot :)

**Comment by flaviocopes** [comment]
Do you mind fixing it in the translation, for fellow germans? https://crowdin.com/project/grav-admin

**Comment by Kuurusch** [comment]
Yea, I think it would be better to translate it to something like "Klassifizierungen" or use the Germanisation of the latin word "Taxonomien".
Because under Taxonomies there is already the entry "Category" and "Tags". So then you have an overall term and beyound the precision.
