### ISSUE TITLE
Search with accented characters not working for some words

### ISSUE THREAD

**Issue by rbukovansky** [getgrav/grav-plugin-simplesearch#95]
I'm trying to make this plugin work for our company's help website (Grav, Learn2), but something weird is happening. When I try to search for a Czech word `pořadač` (folder bin in English) it's found. But for `číselník` ("simple list" in English? Let's say part of information system where you can manipulate with i.e. list of countries), there are no results. And yes, there are pages containing that word. Any idea?

Results of search for `pořadač`:
![poradac](https://cloud.githubusercontent.com/assets/1004491/22929130/64692428-f2ba-11e6-81f8-16c5fd62d296.png)
Results of search for `číselník`:
![ciselnik_search](https://cloud.githubusercontent.com/assets/1004491/22929134/6a3460d4-f2ba-11e6-982d-4563dcb9d03d.png)
Page with word `číselník` in it:
![ciselnik_page](https://cloud.githubusercontent.com/assets/1004491/22929174/8688d77e-f2ba-11e6-971e-520b336e1868.png)

I tried to switch `Ignore accented characters` on and off, but that didn't help.

**Comment by flaviocopes** [comment]
The first word is in a page title. If you create a page with `číselník` in its title, does it appear?

**Comment by rbukovansky** [comment]
Yes, it does... So simplesearch is not searching through the whole page? :slightly_frowning_face:

**Comment by flaviocopes** [comment]
It should, on the Learn site it does. Maybe it's an issue with accented chars, searching for `chceme` shows that page?

**Comment by rbukovansky** [comment]
Ok. And now, for `chceme` it shows just one other page in the search results...

**Comment by rbukovansky** [comment]
That's really strange. It seems like simplesearch indexes all pages except the last one... Oh crap... Sorry, that page doesn't have correct YAML header, that's why it's not indexed properly... :sob:

**Comment by flaviocopes** [comment]
Ok good then :)
