### ISSUE TITLE
 Wrong charset, conversion error

### ISSUE THREAD

**Issue by rsmarples** [getgrav/grav-plugin-simplesearch#98]
Got the bellow error when putting anything in my search on my blog.

iconv(): Wrong charset, conversion from `UTF-8' to `ASCII//TRANSLIT//IGNORE' is not allowed

```
/var/grav/user/plugins/simplesearch/simplesearch.php

    private function matchText($haystack, $needle) {
        if ($this->config->get('plugins.simplesearch.ignore_accented_characters')) {
            setlocale(LC_ALL, 'en_US');
-->            $result = mb_stripos(iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $haystack), iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $needle));
            setlocale(LC_ALL, '');
            return $result;
        } else {
            return mb_stripos($haystack, $needle);
        }
    }
```

Running SimpleSearch v1.10.0 and Grav v1.1.17

**Comment by flaviocopes** [comment]
Looks like a PHP bug on some platforms / setups: https://bugs.php.net/bug.php?id=44096

Turn off `ignore_accented_characters` in the plugin options.

**Comment by rsmarples** [comment]
That helped, thanks. I don't recall toggling that option, but happy to chalk it up to user error.
