### ISSUE TITLE
Button is ignoring min_query_length

### ISSUE THREAD

**Issue by core77** [getgrav/grav-plugin-simplesearch#99]
When the search field is empty and you press the **search button** the 404 page (not found) appears.

When pressing the **enter key**, this doesn't happen.

GRAV v1.1.17
SimpleSearch v1.10.0

**Comment by OleVik** [comment]
Can replicate with the same Grav and SimpleSearch, `event.preventDefault();` is not firing on an empty field as it should. It still navigates to `search/query:`.

**Comment by flaviocopes** [comment]
Thanks @OleVik for the PR
